### PR TITLE
Update badges and workflows

### PR DESCRIPTION
**Pull request by devmotion**
I completely missed that the package uses `main` and not `master` as default branch (BTW CompatHelper seems to work, it also noticed that a key COMPATHELPER_PRIV exists).

### CODE REVIEW

**Comment by phipsgabler** [comment]
Maybe I copied something wrongly.  I generated and added a new key pair now.

**Comment by phipsgabler** [comment]
Is that enough of a check that this is good now: https://github.com/TuringLang/AbstractPPL.jl/runs/2303403984?check_suite_focus=true?  Or will the trigger work differently if there is actually something to update?

**Comment by devmotion** [comment]
Unfortunately, it doesn't ensure that it's correct. The (possibly resolved) problem occurs only when CompatHelper actually opens a PR. Without the key or an incorrect key it can't trigger any other Github actions but this is not relevant for the check if any newer versions exist.

**Comment by phipsgabler** [comment]
Hm, I thought we would notice it the next time CompatHelper runs, but appearently that is not so often.  Do you think I should just merge and wait, or wait for a test case, first?

**Comment by devmotion** [comment]
Oh CompatHelper runs every day at midnight but the error only occurs (or hopefully not anymore...) if it opens a PR which doesn't happen too often since the package only depends on AbstractMCMC IIRC.

**Comment by devmotion** [comment]
So I'd merge the PR without checking it - the worst thing that can happen is that it does not work the next time CompatHelper opens a PR and one has to close and reopen its PR manually to trigger the CI tests.

**Pull request merged**
