### PR TITLE
Provide symbol in `VarName` constructor as type parameter

### PR DESCRIPTION
**Pull request by devmotion**
Constant propagation in the `VarName` does not work reliably as we noticed in https://github.com/TuringLang/DynamicPPL.jl/pull/221. Applying the changes in this PR improves performance noticeably.

IMO there is no reason to keep the existing type-unstable constructor. I deprecated it, therefore it is a non-breaking change.

### CODE REVIEW

**Comment by phipsgabler** [comment]
I completely agree.  This is basically the same effect as the recommendation to use `Val{x}` instead of `Val(x)`, I believe.

**Comment by marius311** [comment]
Following this deprecation, is there any succinct way to do `VarName.((:x,:y,:z))` without the warning?

**Comment by phipsgabler** [comment]
Nothing shorter than `map(n -> VarName{n}(), (:x, :y, :z))`, I think. It's an inherently dynamic operation.

**Comment by phipsgabler** [comment]
I mean, if this were a frequent practical problem, I can imagine a solution similar to `@gensym` where 

```julia
@varnames x y z[1]
```

expands (unhygienically) to 

```julia
x = VarName{:x}()
y = VarName{:y}()
var"z[1]" = @varname(z[1])
```

But unless there's a pressing need, I'll leave it as an exercise for the interested reader.

**Pull request merged**
