### PR TITLE
[Merged by Bors] - Allow name and property interpolation in varnames

### PR DESCRIPTION
**Pull request by phipsgabler**
Implements #46.

Most of this is dependent on my [PR in Setfield.jl](https://github.com/jw3126/Setfield.jl/pull/168) to allow interpolation of properties (so it works only if you `dev` that branch).

It's a bit of a hack though, since `parse_object_lens` behaves a bit weirdly when the innermost value of a lens chain is an interpolation:

```julia
julia> Setfield.parse_obj_lens(@q $name.a)
(:($(Expr(:escape, :_))), :((Setfield.compose)($(Expr(:escape, :name)), (Setfield.PropertyLens){:a}())))

julia> Setfield.parse_obj_lens(@q x.a)
(:($(Expr(:escape, :x))), :((Setfield.compose)((Setfield.PropertyLens){:a}())))
```

I'd be really nice to always get the latter form.  (`@q` is just an ad-hoc macro to construct expressions preserving the `:$`.)

@jw3126, could you maybe look at this and suggest any better alternatives? Either how to implement this nicely in AbstractPPL.jl, or improvements I can add to my PR.

### CODE REVIEW

**Comment by jw3126** [comment]
> behaves a bit weirdly when the innermost value of a lens chain is an interpolation:

It is a feature not a bug :smile: . Until now interpolation meant lens interpolation and `$lens.a` was perfectly fine syntax to specify the composition of `lens` and `@lens _.a`. 

But now we have also "fieldname" interpolation and one might also expect "object" interpolation, which matches your desired parser output.

**Review by yebai — APPROVED** [review]
Many thanks, @phipsgabler for finalising this PR!

**Pull request closed without merging**
